### ISSUE TITLE
Refactore Config

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#109]
On pratical used the Injection of the config can sometimes be hard to handle, specially when requiring a lot of config objects.

**Comment by MarkVink** [comment]
I noticed this issue stating you would like to rewrite the use of Config. I think it also would be nice if there was a way to use a configuration file from outside the java project, or overwriting configuration properties (VM arguments?)

This would be useful in the case;
- You might like to have the configuration file in your version control, except for certain keys like application secret and database credentials.
- You might like to be able to change certain configuration settings without deploying a new jar. An example would be database credentials or application specific properties.

**Comment by svenkubiak** [comment]
"I think it also would be nice if there was a way to use a configuration file from outside the java project, or overwriting configuration properties (VM arguments?)"

That is something, you can already do. Just pass an absolute path to -Dapplication.conf and it will be used instead of the application provided one.

**Comment by MarkVink** [comment]
Alright! I did a search for -D in the documentation but wasn't able to find anything about it, assuming the feature didn't exists. Thanks!

**Comment by svenkubiak** [comment]
I have just updated the documentation on this :-)
