### ISSUE TITLE
Possible information leakage using application timer

### ISSUE THREAD

**Issue by MarkVink** [svenkubiak/mangooio#117]
**Situation**
Recently the feature was introduce to add an X-Response-Time header to your response. This feature could possible leak information when used on controllers where user has to authorise. Take the login process as example;
- When a user provides an invalid username/email address there is no further processing then one request to the database.
- When a user provides a valid username/email address, where will further processing happen like using Bcrypt to verify the password. We do not know yet if the password is valid, just de response have a higher delay with a valid user account.

In fact, we know the response will take longer with a valid username, and this will likely be measurable without the X-Response-Time header. Although with this feature we just give the information for free without having to consider connection lag.

**Solution**
It would be nice to be able to enable/disable this feature in your controller. If this is not possible the documentation should state something about this concern?

**Comment by svenkubiak** [comment]
You have a solid point. But the X-Response-Timer is disabled by default, see 6.1 in the documentation

> mangoo I/O enables you a specific header for this case, which is disabled by default.

Although it can only be set globaly, not per request.

**Comment by MarkVink** [comment]
Then it's the user his responsibility to enable/disable this functionality, and think about implications for his application.
