### ISSUE TITLE
Add 2FA Utility methods

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#139]
Integrate 2FA methods in the authentication class. May use this
https://github.com/j256/java-two-factor-auth/blob/master/README.md

**Comment by WilliamDunne** [comment]
I'd happily have this assigned to me

**Comment by svenkubiak** [comment]
Sure. What are your ideas?

**Comment by WilliamDunne** [comment]
Previously I have used with some success https://github.com/wstrange/GoogleAuth 

I would probably modify this to get rid of some of the cruft, and then use that. Probably a simple helper method that generates twofa secrets, twofa urls (for QR codes), and a helper function to verify the users data. Leave providing the secret when verifying to the controller/whatever.

**Comment by svenkubiak** [comment]
What about the Project I linked to? It just one class which can be easily refactored.

**Comment by WilliamDunne** [comment]
Yeah that might be a better choice, easier to clean. I would use that.
