### ISSUE TITLE
template override not working

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#142]
I have a signup form which is posted to the below method.
public Response signupPost(Flash flash, Session session, Form form) {
I am trying to go back to the signup form using the below code 
return Response.withOk().andContent("signup.ftl", map).end();

However I get the below error
 Template not found for name "ApplicationController/signupPost.ftl".

**Comment by MarkVink** [comment]
You would be able to display correct template with something like `andTemplate("ApplicationController/signup.ftl")`

**Comment by ezcamlive** [comment]
Yes. This worked for me.
return Response.withOk().andTemplate("ApplicationController/signup.ftl").end();

**Comment by svenkubiak** [comment]
Please close, if not an issue any more :-)
