### ISSUE TITLE
Files don't get uploaded

### ISSUE THREAD

**Issue by WilliamDunne** [svenkubiak/mangooio#143]
While the text value of the file (the name of it at least) does successfully get passed into the values map, the file list is empty. Known error?

**Comment by svenkubiak** [comment]
Could you explain a little bit what you we're trying to do? Minor code example would be nice :-)

**Comment by WilliamDunne** [comment]
I don't have the code on me, but there is nothing to fancy to explain.

The project consists of a form in which you can upload two files (two separate file fields), and a submit button, which send a post request to an endpoint which has one parameter - the 'Form'.

In the controller I try and retrieve the files from the Form, but it returns nothing, the size is 0.

However, what I can do is retrieve the file names by iterating through the Map of values, although that is not very useful.

**Comment by svenkubiak** [comment]
Does the single upload with getFile() work?

**Comment by WilliamDunne** [comment]
I did try that straight away, and it didn't work. Also getFile just returns the first value from the list anyway if I remember correctly.

**Comment by svenkubiak** [comment]
ok. I will look into it asap.

**Comment by svenkubiak** [comment]
What ContentType did you set in your form?

**Comment by WilliamDunne** [comment]
Ah that could be it I suppose. I didn't;

```
<form action="/upload" method="post">
   <!--some inputs-->
</form>
```

What would be the appropriate type?

**Comment by svenkubiak** [comment]
enctype="mutilpart/form-data"

**Comment by WilliamDunne** [comment]
I'll have a crack at that later this evening when I get back to it, it never occurred to me that it would make a difference, but that makes sense.

**Comment by MarkVink** [comment]
Good catch, Undertow will only [handle uploads](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java#L80) with multipart/form-data.

**Comment by svenkubiak** [comment]
I did some refactoring in the handler anyway. But file upload should work with the current implementation.

**Comment by svenkubiak** [comment]
i'll close this for now.

**Comment by WilliamDunne** [comment]
I can confirm it works
