### ISSUE TITLE
Big documentation update

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#147]
Documentation needs updates on:

- New cache provider
- New template engine provider
- New template engine
- New 2FA utility methods
- Notes on running multiple instances (Hint: Cache, SSE and WSS information)

Also we need to test the new template engine pebble and the updated OAuth lib.

**Comment by MarkVink** [comment]
Just wondering if there is already some documentation available on how to implement Pebble? :-)

**Comment by svenkubiak** [comment]
Not yet. Still working on adding authenticitytoken and authenticityform to make things complete. So, unfortunatly you'll have to wait for the "Big Documentation Update".
