### ISSUE TITLE
Add ability to set via config maximum upload size

### ISSUE THREAD

**Issue by WilliamDunne** [svenkubiak/mangooio#154]
Undertow defaults to 10mb, should be set in mangoo config.

If no one else snaps it up I'll do it once Two Factor stuff is agreed on

**Comment by svenkubiak** [comment]
ah, ok. good to know. would be nice to have some other options configurable as well. Do you know if there is a list of options for undertow?

**Comment by svenkubiak** [comment]
Looks this is done with UndertowOptions.MAX_ENTITY_SIZE on the ServerBuilder. Any suggestions what also should be configurable via application.yaml from UndertowOptions?

**Comment by MarkVink** [comment]
I didn't look into it, but the mentioned class contains;
```
/**
 * We do not have a default upload limit
 */
public static final long DEFAULT_MAX_ENTITY_SIZE = -1;
```

Does this mean the default upload size already is infinity? Same stated in the [documentation](http://undertow.io/undertow-docs/undertow-docs-1.2.0/#common-listener-options) 

> MAX_ENTITY_SIZE
The default maximum size of a request entity. If entity body is larger than this limit then a java.io.IOException will be thrown at some point when reading the request (on the first read for fixed length requests, when too much data has been read for chunked requests). This value is only the default size, it is possible for a handler to override this for an individual request by calling io.undertow.server.HttpServerExchange.setMaxEntitySize(long size). Defaults to unlimited.

**Comment by WilliamDunne** [comment]
Must have changes, I was researching it and it said the default is 10mb. Definite DDoS vector

**Comment by MarkVink** [comment]
You can always configure the max upload size / request throttling etc on your reverse proxy.

**Comment by svenkubiak** [comment]
@MarkVink Yes, but this is IMHO a rather uncommon approach.
