### ISSUE TITLE
Lifecycle is missing stopped method

### ISSUE THREAD

**Issue by saltnlight5** [svenkubiak/mangooio#178]
It seems the Mangoo's Lifecycle interface is lack of "stopped" method. It would be more complete if you provide such as "destroying" and "stopped" along with what you have.

Also, looking at your Application and Boostrap source, you missed to properly stop the Undertow and and Scheduler. Both of these which have very important cleanup lifecycles on their own.

**Comment by svenkubiak** [comment]
Thanks for the feedback, and yes, this sounds like very good idea. 

As this will break API compatibility I have set this to 4.0.0
