### ISSUE TITLE
Add throtteling to request

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#190]
Add an additonal parameter which enables throtteling of request, e.g. max 5 req/sec.

**Comment by MarkVink** [comment]
Will the max of 5req/sec be applied to each user individually trying to access a certain route, or the route itself?

**Comment by svenkubiak** [comment]
Per user (IP) accessing a specific route.

**Comment by MarkVink** [comment]
Thats cool! 

In that case also reminds that in most cases the app runs behind a reverse proxy which has the pass IP headers.

**Comment by svenkubiak** [comment]
Yes, you're right. We should keep that in mind. Are there alternatives?

**Comment by MarkVink** [comment]
The application has access to (session) cookies for sure, although its not a reliable basis for throttling. So, the application must be sure its provided with an IP address, or its not able to distinguish between users.

**Comment by svenkubiak** [comment]
Moved to 4.0.0 as this requires some new feature from 4.0.0
