### ISSUE TITLE
Delayed completion of request processing

### ISSUE THREAD

**Issue by capablegh** [svenkubiak/mangooio#192]
Hello. I am not sure if the Mangoo forums is monitored by anyone, so posting the following questions here as an issue.

How should an HTTP request be processed if its completion is expected to take long? For example, the processing may involve invoking an RPC/RMI or like call that may take long to complete. There are two consequences of such a delay:
a) The client that send the current request may timeout waiting for a response.
b) The processing of other requests that arrived after this request be blocked

So, would it be more meaningful to send an HTTP 102 or such response? Anything else?

**Comment by svenkubiak** [comment]
Closed, due to anser in forum:
https://mangoo.io/forums/topic/delayed-request-handling/#post-643
