### ISSUE TITLE
ClassNotFound Exceptions org/eclipse/jetty/WebSocket/Session

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#214]
When using Fluentlenium tests, the above class occours

current fix is to donwgrade htmlunit-driver from mangoo I/O test project

```xml
		<dependency>
			<groupId>io.mangoo</groupId>
			<artifactId>mangooio-test</artifactId>
			<version>${mangooio.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>htmlunit-driver</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>htmlunit-driver</artifactId>
			<version>2.20</version>
		</dependency>
```

**Comment by svenkubiak** [comment]
Fixed by downgrading to htmlunit 2.21. Still needs fixing for latest version.

See: https://github.com/SeleniumHQ/htmlunit-driver/issues/22

**Comment by svenkubiak** [comment]
Fixed for now by including the websocket-client dependency in the mangooio-test project.

**Comment by ThrawnCA** [comment]
As I've mentioned in https://github.com/SeleniumHQ/htmlunit-driver/issues/22, I believe that including websocket-client is the correct fix. Although I personally don't think that htmlunit-driver should be specifically excluding it, since its default configuration relies on it...
