### ISSUE TITLE
debugging mangooio:run

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [svenkubiak/mangooio#222]
There seems to be no option to debug the application via an IDE (with breakpoints) may be add an environment variable MANGOOIO_OPTS and include them in Runner.java while launching the Application? or is there a way to do this

**Comment by svenkubiak** [comment]
To be honest, I did not have the use case to debug the maven goal. But this sounds like a nice enhancement. Any concrete ideas on how to do this?

Cheers,
Sven

**Comment by gowthaman-basuvaraj** [comment]
the best way would be to add a parameter to plugin configuration something like "jpda.port" with some default value say 4000 and start the jpda in dev mode 

the other way would be including the value of a particular environment variable (MANGOOIO_OPTS) while starting the JVM in Runner.java (buildProcessExecutor function) 

i'll prefer Method 1) enabled by default so by  a debug connection can be made to the app from the IDE without needing for any change by the user

**Comment by svenkubiak** [comment]
Sounds good. Feel free to fire a pull request ;-)
