### ISSUE TITLE
Moving config/controllers outside of root

### ISSUE THREAD

**Issue by wildunne** [svenkubiak/mangooio#226]
Long time no speak!

Just wondering, when I try and move the config/controllers package into another package (i.e into com.example.config/controllers) Mangoo fails to run. On the routes.yaml it gets a class not found exception with the line below:

`- GET:    /     ->    com.example.controllers.ApplicationController.index`

And a null exception on the LifeCycle not being found.

How can I do this?

**Comment by wildunne** [comment]
ApplicationController.index

yields cannot find class controllers.ApplicationController, but I cannot see a config place to set this...

**Comment by MarkVink** [comment]
There is a configuration option to change the default package for your controllers. In your route you would still only refer to the correct classname 'ApplicationController.index'

```
default:
    application:
        controller : com.example.controllers

**Comment by wildunne** [comment]
Thanks!
