### ISSUE TITLE
Binary Content always serves content type as "application/octet-stream"

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#227]
There should be a way to set the content type for binary conent
exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, ContentType.APPLICATION_OCTET_STREAM.toString());

**Comment by MarkVink** [comment]
It is possible to set the content type of the response using the following code in your controller.

```
        return Response.withOk()
                .andContentType(ContentType.APPLICATION_OCTET_STREAM.toString())
                .andBinaryContent("Some content".getBytes());

**Comment by ezcamlive** [comment]
I tried that eturn Response.withOk()
                .andContentType("image/jpeg")
                .andBinaryContent("Some content".getBytes());

**Comment by MarkVink** [comment]
You are correct, BinaryHandler.java always set the content type to "application/octet-stream"

**Comment by ezcamlive** [comment]
Why? I want to serve binary content with other content types. Ex: pdf, jpeg, etc

**Comment by svenkubiak** [comment]
@MarkVink was right, but the example not quiet correct ;-)

You can overwrite all headers by setting them in the controller method. 

```
        return Response.withOk()
                .andHeader(Headers.CONTENT_TYPE, "MyContentType")
                .andBinaryContent("Some content".getBytes());

But i'll agree that the andContentType method is misleading here as it is not used in the BinaryHandler.

**Comment by svenkubiak** [comment]
I have just release a bug fix release (should be on maven central soon) which should address this issue.
