### ISSUE TITLE
Custom DispatcherHandler or ability to customize getMethodParameters in DispatcherHandler

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [svenkubiak/mangooio#231]
I am very fond of using Kotlin for all my projects, however there is a small catch to it, the Kotlin Compiler Does not Write parameter names of the function in the class, its always arg0, arg1 etc ...,  due to which mangoo is unable to set parameter values to the function from the Url/Query parameters

```

class AppCtrl {
   fun get(id: Long?): Response {
     return Response.withOK().andTextBody("You asked for $id")
   }
} 

```

in routes.yaml

```
GET: /app     ->   AppCtrl.get
GET: /app/{id}     ->   AppCtrl.get
```

While Trying to load `/app?id=1` or `/app/1` id is always null 

so my question is How can we go about this, this being a very specific requirement for one Jvm Language(the parameter part) it should **not** be a part of mangoo core 

So i am wondering would it make sense to 
- let  users give their Own version of DispatcherHandler  (minor change to core)
- like [play framework routes](https://playframework.com/documentation/2.5.x/JavaRouting) `GET: /app/{id}   -> AppCtrl.get(id: Long)` (major change to core)

What would be a good solution?

**Comment by MarkVink** [comment]
Maybe it helps, a similar issue was discussed earlier #130.

**Comment by svenkubiak** [comment]
I understand you specific requirments. But to be honest, one of the fundamentals of mangoo I/O is that it is pure java. Thus, it beeing a Java framework - not a Jvm framework.

That beeing said, making the DispatchHandler custom (like the other handlers are already) through guice bindings. But I realy would prefer having this as an extension, rather than in the core.

Cheers,
Sven

**Comment by gowthaman-basuvaraj** [comment]
agreed it should be in a module or even in the application and not in the framework, and may be via a Guice Provider it can be instantiated , will see which one would be clean to implement and maintain

**Comment by gowthaman-basuvaraj** [comment]
With the release of Kotlin 1.1, this is resolved, it writes correct parameter names similar to java8 compiler, closing this for now.
