### ISSUE TITLE
Release 3.9.0

### ISSUE THREAD

**Issue by MarkVink** [svenkubiak/mangooio#234]
Hey,

I noticed in the codebase that you released version 3.9.0 about two weeks ago. Although this version cannot be found in the Maven repository

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.mangoo%22%20AND%20a%3A%22mangooio-core%22

**Comment by svenkubiak** [comment]
Oh, crap. Thanks for noticing. It was missing one release click in the Nexus Repository Manager. Should be on maven central soon.

Best,
Sven
