### ISSUE TITLE
Cache Enhancement

### ISSUE THREAD

**Issue by MarkVink** [svenkubiak/mangooio#235]
I'm building an API where I would like to cache certain responses for a limited period of time. Since I'm returning Json (objects) it's easy to just store the object in the default Cache provided by Mangoo. I do not want to cache responses on my reverse proxy since there is logic involved.

Currently it is not possible - neither with 3.9.0 or 4.0.0 beta - to configure your own expiry for the default cache. The CacheProvider on the 4.0.0 branch looks really promising in providing flexibility, although it seems not be possible to create your own caches with the CacheManager, or configure your own expiry.

Therefore I think it would be a nice enhancement if we are able to configure the hardcoded settings in the CacheProvider - maybe using ehcache.xml, or providing a way to register your own Cache instances with the CacheManager.

Right now the solution would be to use the Guava/EhCache yourself to set the expiry, while Mangooio tries to provide an easy solution out of the box.

**Comment by svenkubiak** [comment]
Hi,

for the exact problem you have, I decided to go with the CacheProvider. However, currently its only used for the different cache mangoo I/O needs for internal stuff, but its the starting point.

Currenty focus is on bringing 4.0.0 to live, but fully agree on what you suggest.

**Comment by MarkVink** [comment]
What would be the desired solution; Making the internal cache settings configurable or providing a way to register your own cache to the manager?
