### ISSUE TITLE
How to add a directory for static files just like assets and fall back to that directory if a route is not available?

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#243]
Example: I have a directory dist under files and would like to serve files such as /index.html from there unless there is already a route mapped.
-PATH /dist /

**Comment by svenkubiak** [comment]
From the top of my head I would suggest creating a custom FallbackHandler. Or, if is just for 404 Not Found you could just customize the 404 template in your project, overwriting the default one from the framework.

**Comment by ezcamlive** [comment]
Thanks. It's the former. Static pages are created by a separate process so just trying to keep them separate.

**Comment by MarkVink** [comment]
If it's the case that those static files are created by an entirely separated proces, and also stored just somewhere on your server, you could consider solving your problem on the reverse proxy - nginx for example; Use try_files to check for the existence of the file, otherwise pass the request to the sunning Mangoo application suing proxy_pass.

**Comment by ezcamlive** [comment]
I do have haproxy but need to see how try files work. That may be a better approach. Thanks.

**Comment by svenkubiak** [comment]
afaik, haproxy is "just" a loadbalancer. Also I dont't have much experience with it, he will probably wont have a feature like try_files.

**Comment by ezcamlive** [comment]
Yes. It cannot server http just a proxy. Switching to Caddy since I don't want another web server to server http.

**Comment by svenkubiak** [comment]
Is this still an issue or can I close it?

**Comment by ezcamlive** [comment]
You can close it. I use caddy now to front the application.
