### ISSUE TITLE
Is Pebble template engine going to be supported in version 4? 

### ISSUE THREAD

**Issue by dmarko484** [svenkubiak/mangooio#245]
Is Pebble template engine going to be supported in version 4? Can't find it in current RC releases ...

**Comment by svenkubiak** [comment]
With the upcoming release 4.0.0, Pebble will not be part of the core anymore. But it will be release as a separate module, so you can still use Pebble with mangoo I/O.

**Comment by svenkubiak** [comment]
I just created the repo and will release version 1.0.0 asap. Please note, that unit tests and extended documentation is missing atm.

https://github.com/svenkubiak/pebble-mangooio-extension

**Comment by ezcamlive** [comment]
Can't find the source code.

**Comment by svenkubiak** [comment]
Pebble is not supported anymore.
