### ISSUE TITLE
Controllers in Sub Packages

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [svenkubiak/mangooio#264]
the routing breaks if the controllers are in sub-packages

working:

```
- method: GET
  url: /
  mapping: ApplicationController.index
```

Not working:

```

- method: GET
  url: /api/v1/operator
  mapping: operator.OperatorListAPI.get
```

I have made a change in my branch to make it work, should i send a pull request? i see that as part of v5 routes.yaml is not needed?

**Comment by svenkubiak** [comment]
Yes, this os obsolet with upcoming version 5.0.0. But as we probably won't this this version this year, a fix would be great.
