### ISSUE TITLE
If "application.secret" is started with zero and contains only numbers, application can not be started

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#269]
`secret: 01234567890123456789012345678901234567890123456789012345678901234567890`

> 14.03.2017 18:03:33,178 [main] ERROR io.mangoo.core.Bootstrap - Please make sure that your application.yaml has an application.secret property which has at least 32 characters

`secret: 1234567890123456789012345678901234567890123456789012345678901234567890`

> 14.03.2017 18:05:13,998 [main] INFO  io.mangoo.core.Bootstrap - mangoo I/O application started in 1450 ms in dev mode. Enjoy.

`secret: 0qwerty1234567890123456789012345678901234567890123456789012345678901234567890`

> 14.03.2017 18:05:46,441 [main] INFO  io.mangoo.core.Bootstrap - mangoo I/O application started in 1466 ms in dev mode. Enjoy.

**Comment by svenkubiak** [comment]
Thanks for reporting this. I will look into it.

**Comment by svenkubiak** [comment]
It looks like this is part of the YAML specification. Everything starting with "0" is treated as ocal.
http://girders.org/blog/2009/08/13/ruby-yaml-loads-leading-zero-numbers-as-octal/

If you quote your secret ("") then it works. However, I just would not use only numbers though 😄

**Comment by ismagilov** [comment]
Seems, like you are right. Here are two link for YAML spec:
http://yaml.org/spec/1.2/spec.html#id2764652
http://yaml.org/spec/current.html#id2507367 (in later YAML versions octal numbers should be started with "0o").

As an alternative to "", you can escape leading zero with "\". This secret works: 
`secret: \01234567890123456789012345678901234567890123456789012345678901234567890`.

**Comment by svenkubiak** [comment]
Ok. Thanks for digging into this. I'll close this for now.
