### ISSUE TITLE
How can mangoo app be debugged in IDE (IDEA in my case)?

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#275]
I am using IDEA and can not figure out how to debug running application? Firstly, I run `mvn clean package`. Then `mvn manoogio:run` in Debug IDE mode (see attachment). Then I see this output: 

> /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59238,suspend=y,server=n -Dmaven.multiModuleProjectDirectory=/Users/ilya/Work/Projects/todobackend-mangooio "-Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" org.codehaus.classworlds.Launcher -Didea.version=2016.3.5 mangooio:run
Connected to the target VM, address: '127.0.0.1:59238', transport: 'socket'
[INFO] Scanning for projects...
 
Not sure that it is correct way, especially, if `mangooio:run` forks JVM...

<img width="375" alt="screen shot 2017-03-21 at 18 49 24" src="https://cloud.githubusercontent.com/assets/6725061/24146234/6f11dd5c-0e67-11e7-8836-040a3469072a.png">

**Comment by MarkVink** [comment]
Take a look at this issue #228 for remote application debugging.

**Comment by ismagilov** [comment]
It worked! Many thanks for helping and sorry for being inattentive. Info about `jpda` is written to the output log: 
> 17:42:15.629 [DelayedRestartTrigger] INFO  io.mangoo.build.Runner - Listening for jpda connection at 8000
Listening for transport dt_socket at address: 8000

Nevertheless, probably it is a good new topic to be covered in docs 😄

**Comment by svenkubiak** [comment]
Yes. The documentation is not up-to-date on all parts. See #253
