### ISSUE TITLE
Add OPTIONS method for Routing

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#276]
I was trying to implement a sample application with CORS support: [CORS tutorial](https://www.html5rocks.com/en/tutorials/cors/)

Support of `OPTIONS` method is very important for making online services CORS-friendly. It is needed for *preflight* requests.

As far as I can see, this method is not supported: https://docs.mangoo.io/routing.html.

When I am trying to send REST request using `OPTIONS` method, I get this response:
> HTTP/1.1 405 Method Not Allowed
Connection: keep-alive
Content-Length: 0

**Comment by svenkubiak** [comment]
This should be an easy fix, but there will be no out-of-the-box functionality for the request type. So you have to implement the required headers according to the specs yourself.

http://zacstewart.com/2012/04/14/http-options-method.html

**Comment by ismagilov** [comment]
Sure. In the majority of frameworks it is done though separated modules/filters. In my case, probably, global filter will be used...

**Comment by ismagilov** [comment]
Thanks for fixing! Where can I get the most recent version? Do you have some kind of "nightly builds"?

**Comment by svenkubiak** [comment]
Currently there are no nightly build. If you want to check out the latest version you need to checkout  the required branch and install it into your local repository.
