### ISSUE TITLE
Global filter is not called when doing simple GET request

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#277]
For full sample code you can see in a project: https://github.com/ismagilov/todobackend-mangooio

Briefly speaking, what I did.

1. Created a global filter:
```
package filters;

public class CorsFilter implements MangooRequestFilter {
    public Response execute(Request request, Response response) {
        System.out.println("Global filter is executed");
        return response;
    }
}
```

2. Added new route:
```
- method: GET
  url: /todo
  mapping: ApplicationController.todo
```

3. Added controller-level filter for testing:
```
package filters;

public class SimpleFilter implements MangooFilter {
    @Override
    public Response execute(Request request, Response response) {
        System.out.println("Simple filter is executed");
        return response;
    }
}

```
```
@FilterWith(SimpleFilter.class)
public class ApplicationController {
    public Response todo() {
        return Response.withOk().andJsonBody("TODO");
    }
}
```

4. Visited http://localhost:9090/todo and successfully saw "TODO" on a page.

5. In the output I got only: `Simple filter is executed` without `Global filter is executed`

**Comment by MarkVink** [comment]
In your Module.java you can bind a global filter.

```
@Singleton
public class Module extends AbstractModule {

    @Override
    protected void configure() {
        bind(MangooLifecycle.class).to(Lifecycle.class);
        bind(MangooRequestFilter.class).to(ApiAuthenticationFilter.class);
    }
}
```

**Comment by svenkubiak** [comment]
What @MarkVink wrote is exactly the missing link. You need to bind your gloabal filter in the Module.java so that the framework knows, which class to call. Sorry for that beeing not in the docs.

**Comment by ismagilov** [comment]
Many thanks for the explanation! Now it works 😄
