### ISSUE TITLE
URL parameter /{id} is not passed into controller method

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#292]
Controller method:
```
    public Response get(String id) {
        System.out.println(id);

        return Response.withOk().andEmptyBody();
    }
```

Routes:
```
- method: GET
  url: /
  mapping: ApplicationController.getAll

- method: GET
  url: /{id}
  mapping: ApplicationController.get
```

When I fire GET request `.../1`, I see this output:
```
11.04.2017 13:31:01,739 [main] INFO  io.mangoo.core.Bootstrap - mangoo I/O application started in 1820 ms in dev mode. Enjoy.
null
```

What is wrong in my mapping? Besides, I have posted a comment in docs that it lacks description of what kind of mappings are supported, except static non-parameterised URLs.

**Comment by svenkubiak** [comment]
Are you in dev mode? See https://docs.mangoo.io/your-first-application.html -> Using hot-compiling in dev mode. I am pretty sure, that this is the reason, why your paramter is null. 

If have added a point to the list for documentation improvements in regards to paramter handling. Looks like it got lost when we moved from the "old" homepage to GitBook.

**Comment by svenkubiak** [comment]
BTW: I have no clue where it went, but there was a complete plage dedicated to request and query parameter.

https://www.gitbook.com/book/svenkubiak/mangoo-i-o/build/5899c2fff334a61100849873

**Comment by ismagilov** [comment]
> Are you in dev mode? See https://docs.mangoo.io/your-first-application.html -> Using hot-compiling in dev mode. I am pretty sure, that this is the reason, why your paramter is null.

Thanks for pointing! It helped.

**Comment by svenkubiak** [comment]
You're welcome 😄

**Comment by svenkubiak** [comment]
> What is wrong in my mapping? Besides, I have posted a comment in docs that it lacks description of what kind of mappings are supported, except static non-parameterised URLs.

Documentation on controllers is back online again:
https://docs.mangoo.io/controllers.html

**Comment by ismagilov** [comment]
A huge, important and very helpful part was missing! Thanks!
