### ISSUE TITLE
Need Reference to Controller/Method in Filters

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [svenkubiak/mangooio#294]
I have an annotation 

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface AllowIf {
    Permission[] value();
}
```
and i want to Annotate the method with it, citing allowed permissions

```
    @AllowIf(Permission.UPD_PORT_PROPERTIES)
    public Response cfgState(ConfigState configSave) throws IOException {
      

        return Response.withOK().andJsonBody(configSave)
    }
```

I am looking for the ability to check the annotated permissions and if the user does not have any of the assigned permission then a Forbidden response can be sent

At present, I think there is no way to get the Controller Class/Method, I could try doing an Url match with the list of routes but that'll be error prone.

Is it possible or am I missing something?

if not, then adding the controllerClass and controllerMethodName from Attachment to the Request object will be suffice

**Comment by svenkubiak** [comment]
You would probably need an own classpath scanner for annotation. Why don't you use the build-in filter mechanism?

**Comment by gowthaman-basuvaraj** [comment]
i had not been more clear.

I use a Filter too, what i'd like to do is in the Filter Read the Annotation and Decide

```

public class PermFilter implements MangooFilter {
    @Override
    public Response execute(Request request, Response response) {
        Class<?> controllerClass = request.getControllerClass();
        String controllerMethodName = request.getControllerMethodName();
        
        AllowIf allow = controllerClass.getMethod(controllerMethodName).getAnnotation(AllowIf.class);
        //logic
        return response;
    }
}

```

For that i'll need the Controller Class and Method

**Comment by svenkubiak** [comment]
As you have the URL, you could try a reverse lookup, using the router class.

```
    /**
     * Retrieves a reverse route by its key
     * 
     * @param key The passed route information (e.g. /foo/{bar})
     * @return A route object based on the given controller and method or null if none found
     */
    public static Route getReverseRoute(String key) {
        return reverseRoutes.get(key);
    }
```

Based on that you get the route object with the controller class and method.

**Comment by gowthaman-basuvaraj** [comment]
Nope, It wouldn't work

if i have a mapping like this

```
- method: GET
  url: /api/{tenantId}/vendor
  mapping: tenant.VendorAPI.get
```
the equivalent item in Reverse Router would be `VendorAPI:get` which will give a null pointer if i try to access by Url 

or rather the reverse router is populated by this way 

`            reverseRoutes.put(route.getControllerClass().getSimpleName() + ":" + route.getControllerMethod(), route);    
`
so there is no way to get the route from the Url

**Comment by svenkubiak** [comment]
Ah, sorry. You need a similar method but the opposite way. The JavaDoc is misleading hear also.

As there is not build-in method for the lookup you need, you could access the routes through 

`Router.getRoutes()`

This will give you all configured routes. From there you could iterate through the routes and get the route you need based on the URL. This should work.

**Comment by gowthaman-basuvaraj** [comment]
For static URLs (/index, /home, etc ..) it'll work but for Url, with parameters (`/api/{customer_id}/orders`) there'll be a need for some comparison and it'll be tricky to get it correct in all scenarios (like nested parameters `/api/{customer_id}/order/{order_id}` ).

What i propose is add `controllerClass and controllerMethodName as a part of Request Class` and populate it in `RequestHandler.getRequest` method.

i have it in my branch and it works well

**Comment by svenkubiak** [comment]
Can we close this?
