### ISSUE TITLE
Add PATCH to availabel HTTP methods

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#295]
Issue is similar to this one: #276. 

The method is important for composing REST API: http://www.restapitutorial.com/lessons/httpmethods.html.

**Comment by svenkubiak** [comment]
http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/ 😄

**Comment by ismagilov** [comment]
Yes, this method is questionable. But I see, that you have decided to add it? Thanks!
