### ISSUE TITLE
What are best practices to have good performance when almost all controller methods make blocking JDBC calls?

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#301]
As far as I understand, Undertow uses just a few threads to process requests. They a called NIO or IO threads?... It doesn't use traditional one-thread-per-request model. So for good performance it is crucial to exit controller methods as soon as possible. But sometimes it is impossible because of blocking operations, for sample, calling SQL through JDBC. 

The framework supports long-running controller methods using 'blocking: true': https://docs.mangoo.io/routing.html. I can guess that in this case Undertow starts using thread pool and actually falls back to traditional one-thread-per-request model. 

The majority of traditional web apps access SQL through blocking JDBC calls. And I have a feeling, that 95% of all controller method do it. So in fact, you have to mark almost all controller methods as 'blocking: true'. And as a result, you eliminate performance of Undertow IO-threads based model.

Do you have some ideas (or experience with using the framework in real-world apps) about how to workaround this situation and process blocking calls effectively without forcing Undertow to fall back to traditional thread model? Can you share them with us?

P.S. Maybe I misunderstand something in general. I will appreciate, if you correct me.

**Comment by svenkubiak** [comment]
`As far as I understand, Undertow uses just a few threads to process requests. They a called NIO or IO threads?`

Correct. XNIO http://xnio.jboss.org/

`It doesn't use traditional one-thread-per-request model. So for good performance it is crucial to exit controller methods as soon as possible.`

I wouldn't put it that generic black and white. one-thread-per-request model can also be performant. This needs individual performance measurment to dertermine the right approach.

`The framework supports long-running controller methods using 'blocking: true': https://docs.mangoo.io/routing.html. I can guess that in this case Undertow starts using thread pool and actually falls back to traditional one-thread-per-request model.`

I am actually not sure if undertow drops to a one-thread-per-request model. This is from the offical documentation:

> By far the most common use of HttpServerExchange.dispatch() is to move execution from an IO thread where blocking is not allowed into a worker thread, which does allow for blocking operations.

`The majority of traditional web apps access SQL through blocking JDBC calls. And I have a feeling, that 95% of all controller method do it. So in fact, you have to mark almost all controller methods as 'blocking: true'. And as a result, you eliminate performance of Undertow IO-threads based model.`

IMHO this can not be answered in a genric way. Yes, if you make all requests blocking you fallback to a different methodolgy of handling request. But I wouldn't say that you make undertow "slow" with that. Again, this needs individual performance testing on the application.

However, as you will have this "problem" with probably all web frameworks out there, why not turn the other way around and challenge the use of blocking JDBC calls. There are a lot of alternatives to store data these days.

**Comment by svenkubiak** [comment]
Any update on this? Otherwise I would like to close this question.

**Comment by ismagilov** [comment]
@svenkubiak, thanks for your answer! Yes, it can be closed.
