### ISSUE TITLE
Request and query parameter not working

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#38]
I am using 1.0.0-RC4-SNAPSHOT
Request and query parameter is not working

Router.mapRequest(Methods.GET).toUrl("/activate/{key}").onClassAndMethod(ApplicationController.class, "activate");

public Response activate(String key) {

accessing /activate/12355 does not set the value for key  as 12355

**Comment by svenkubiak** [comment]
Does this happen in dev mode? I am pretty sure this happens because the method parameters are not passed due to a missing configuration of your IDE. Check the documentation on how to enable java 8 method parameter passing.

**Comment by ezcamlive** [comment]
Yes. It is dev mode. I run it from command line maven. Let me read about java 8 method parameters.

**Comment by svenkubiak** [comment]
You can read about it on "Important" in section 2.2 of the documentation.

**Comment by ezcamlive** [comment]
I tested by creating a new application using maven archetype and it worked.

In my previous attempt I had built mangooio from source and then made changes 2 files. Let me find out why. But you can close this.
