### ISSUE TITLE
Content-Type: application/json; charset=utf-8

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#48]
Form parsing does not work when charset is part of content type. Unfortunately some http client libraries add charset to content type.

Content-Type: application/json; charset=utf-8

**Comment by svenkubiak** [comment]
Do you have an example? What exactly does not work on form parsing?

**Comment by ezcamlive** [comment]
Here is an example. login object is parsed as null when header is Content-Type: application/json; charset=utf-8 but works when header is Content-Type: application/json
I got around it by changing the client library (okhttp).

Controller.
	public Response login(models.Login login) {
       
Model. Excluding getters and setters
public class Login {
	String usr;
	String pwd;

**Comment by ezcamlive** [comment]
I think this is where it's checking for the exact header.

package: mangoo.io.routing.handlers
Class: public class RequestHandler implements HttpHandler {
Line of code:
((ContentType.APPLICATION_JSON.toString()).equals(exchange.getRequestHeaders().get(Headers.CONTENT_TYPE).element())) {

**Comment by svenkubiak** [comment]
Ah, okay. So its actually the JSON Mapper and not the actual Form parsing. I'll fix this with the upcoming 1.1.0 release, scheduled for September 23rd (will probably be sooner) as the RequestHandler will recieve a majro refactoring anyway.

**Comment by svenkubiak** [comment]
Fixed.
