### ISSUE TITLE
Template Variables

### ISSUE THREAD

**Issue by name256** [svenkubiak/mangooio#555]
Good day,

I am developing an application which requires having a password protected back end. I am able to complete all the login & logout actions in the controller but I am having a challenge accessing the Subject variable to check whether one is actually logged in or not.

<#if subject.authenticated>
	Hello ${subject.username}!
	//Display navigation for authenticated user
<#else>
	Hello Guest!
	//Display navigation for not authenticated user
</#if>

Kindly let me know whether there are any updates that you have done to the code base for the same. I am using version 7.8.0.

Regards

**Comment by svenkubiak** [comment]
Hello there,

really sorry, that the documentation is outdated here. Unfortunately, there is no subject variable anymore that is passed to the template. In order to achieve what you want to do you need a filter that checks for a valid authentication and then passes the subject to the template, e.g.

```
public class GlobalFilter implements OncePerRequestFilter {
    
    public GlobalFilter () {
    }

    @Override
    public Response execute(Request request, Response response) {
        String subject = request.getAuthentication().getSubject();
        response.andContent("subject", subject);
        return response;
    }
}
```
```
<#if subject??>
Hello ${subject}!
//Display navigation for authenticated user
<#else>
Hello Guest!
//Display navigation for not authenticated user
</#if>
```

**Comment by name256** [comment]
Hi,

Thanks for the prompt response. I shall implement as advised.

Kind regards
