### ISSUE TITLE
Version 1.1.2 and Refactored dev mode exception template (svenkubiak) - problem with freemarker error.

### ISSUE THREAD

**Issue by dmarko484** [svenkubiak/mangooio#59]
New exception error page is great but freemarker errors cause white screen only.  Can this be adjusted to see understandable freemarker error message in browser?

**Comment by svenkubiak** [comment]
Thanks. But the credit goes to Play, as the template is just refactored. As for the error, do you mean, when an exception occurs while rendering the exception template?

**Comment by dmarko484** [comment]
You can, for example, eference some nonexisting variable in freemarker template e.g.  ${something} and it makes a blank screen in browser.

**Comment by svenkubiak** [comment]
Ok. I'll look into it.

**Comment by svenkubiak** [comment]
Should be fixed with the upcoming 1.1.3 release.

**Comment by dmarko484** [comment]
Great!!

**Comment by svenkubiak** [comment]
Just release 1.1.3 which should be on maven central shortly. Could you please check the error and re-open this ticket if the bug still occurs. Thanks.

**Comment by dmarko484** [comment]
Just confirming ... working fine ...
