### ISSUE TITLE
Shutting Down Mongo

### ISSUE THREAD

**Issue by name256a** [svenkubiak/mangooio#594]
Hello,
Is there a way that I can shut down the Embedded MongoDB during production?

**Comment by svenkubiak** [comment]
Yes, you can use the stop method to shutdown the Embedded MongoDB

```
EmbeddedMongoDB embeddedMongoDB = EmbeddedMongoDB.createAndStart();
embeddedMongoDB.stop();
```

**Comment by name256a** [comment]
I was able to shut it down. Thank you very much and good day.
