### ISSUE TITLE
static mapping question

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#81]
I created a static page under /files/
and mapped it like below and it works.
Router.mapResourceFile().toUrl("/index.html");

How do I redirect requests to / to /index.html?

**Comment by svenkubiak** [comment]
You can do a redirect in a controller by calling

    return Response.withRedirect("/");

As for your example, the static file can, but shouldn't be used for static html. The purpose of the static files is mainly for Assets. I suggest you load your index.html in the cache and server the content via a normale request like

   return Response.withOk().andBody(htmlContent);

**Comment by ezcamlive** [comment]
I can do this. But why I have to use a controller rather than serving them like any other static content/asset?

I have some static html content manged by a grunt. I just wanted to serve those as static assets.

**Comment by svenkubiak** [comment]
Sury, you can serve your index.html as static content, but you can't do a redirect in the routing configuration. At the moment this can only be done in a controller.

**Comment by svenkubiak** [comment]
Can I close this issue?

**Comment by ezcamlive** [comment]
Yes. Please.
