### ISSUE TITLE
Documentation error on form-handling

### ISSUE THREAD

**Issue by MarkVink** [svenkubiak/mangooio#97]
The [documentation](https://mangoo.io/documentation#_showing_error_messages_in_a_template) is stating regarding templates;
- form.hasError("myField") checks if field has an error
- form.error("myField) displays error

However, the [Form](https://github.com/svenkubiak/mangooio/blob/master/mangooio-core/src/main/java/io/mangoo/routing/bindings/Form.java) object which is passed to the [TemplateEngine](https://github.com/svenkubiak/mangooio/blob/master/mangooio-core/src/main/java/io/mangoo/templating/TemplateEngine.java), does not contain such methods.

Possible solution;
- Change Form object to be consistent with docs.
- Alter docs to use form.validation().hasError("myField") and form.getError("myField") instead.

**Comment by svenkubiak** [comment]
Thanks for reporting!

I have re-added the form.hasError method to the Form object. The form.error in the doc is correct, as Freemarkert omits the "get" when rendering.

**Comment by MarkVink** [comment]
Thanks! Are you sure Freemarker does omit the get?

```
FTL stack trace ("~" means nesting-related):
	- Failed at: ${form.error("email")?cap_first} auto...  [in template "AuthController/login.ftl" at line 19, column 70]
	~ Reached through: #nested  [in template "base.ftl" in macro "base" at line 33, column 5]
	~ Reached through: @layout.base "Login"  [in template "AuthController/login.ftl" at line 2, column 1]
````

**Comment by svenkubiak** [comment]
Well.. I was pretty sure, until i checked the integration-tests. 

Just updated the docs ;-)
